@startuml Use Cases

actor User as U
actor "Liquidity Provider" as LP

actor "Auto Options Selling Protocol" as Prot
actor "Degen" as D

LP <|-up- Prot
LP <|-up- D

package "Options Market" {
    usecase "Buy Option" as BO
    usecase "Excercise Option" as EO
    package "Liquidity Pool" as Pool {
        usecase "Provide Liquidity" as PL
        usecase "Remove Liquidity" as RL
    }

    BO .up.> Pool
    EO .up.> Pool
}

U -up-> BO
U -up-> EO
LP -down-> PL
LP -down-> RL

@enduml